### ISSUE TITLE
Handle error for non-existent output variable

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-HPXML#1060]
```
$ /c/openstudio-3.4.0-rc1/bin/openstudio.exe workflow/run_simulation.rb -x workflow/sample_files/base.xml --add-timeseries-output-variable "Made up"
HPXML: C:/OpenStudio/OpenStudio-HPXML/workflow/sample_files/base.xml
Creating input...
Running simulation...
Completed simulation in 3.4s.
Processing output...
Processing output unsuccessful.
See C:/OpenStudio/OpenStudio-HPXML/workflow/sample_files/run/run.log for details.
```

run.log:
```
Error: Measure Failed with Error: undefined method `[]' for nil:NilClass
C:/OpenStudio/OpenStudio-HPXML/ReportSimulationOutput/measure.rb:1696:in `get_report_variable_data_timeseries_key_values_and_units'
C:/OpenStudio/OpenStudio-HPXML/ReportSimulationOutput/measure.rb:828:in `block in get_outputs'
C:/OpenStudio/OpenStudio-HPXML/ReportSimulationOutput/measure.rb:827:in `each'
C:/OpenStudio/OpenStudio-HPXML/ReportSimulationOutput/measure.rb:827:in `get_outputs'
C:/OpenStudio/OpenStudio-HPXML/ReportSimulationOutput/measure.rb:487:in `run'
```

Need to throw a more useful error message.

**Comment by shorowit** [comment]
Nice catch. It's possible this was working correctly before my switch to MessagePack. Either way, I'll fix this.
